### ISSUE TITLE
Assignment link

### ISSUE THREAD

**Issue by TheSunnyDev** [labrocadabro/100devs-hw-tracker#3]
Thank so you much for providing this helpful resource. It's really helping me catch up!
The link in Class 36 for - Watch: What the heck is the event loop?, links to the Interview Questions (Behavioral / Technical) Google Doc instead.
I believe this is the video: https://www.youtube.com/watch?v=8aGhZQkoFbQ

**Comment by labrocadabro** [comment]
Thanks for the heads up! Fixed :)
