### ISSUE TITLE
Homework for class 29 is missing

### ISSUE THREAD

**Issue by neirobic** [labrocadabro/100devs-hw-tracker#9]
**Hey hey! The tracker says there's no homework for class 29, but I just finished watching the VOD and there's actually a fair bit of homework!**
**He wants us to:**

- Do something with the pokemon API (there's a folder that's specifically set up for that in the materials folder for this class)
- Watch Object-oriented Programming in Javascript: Made Super Simple (https://www.youtube.com/watch?v=PFmuCDHHpwk)
- Read/Do the JS way chapter 09 - https://github.com/thejsway/thejsway/blob/master/manuscript/chapter09.md

**Push:**

- -Read/Do Eloquent JS chapter 06

--
here is the link to the specific slide with the homework, and a screenshot from it.
https://slides.com/leonnoel/100devs2-javascript-review-back-from-break#/66
![image](https://user-images.githubusercontent.com/110944748/201251985-a5335ee9-f415-412e-ae8d-35b13c3259fd.png)

Currently, the readings are listed as being assigned during class 30, but he actually assigns them in this class. : )
and there's no mention of the OOP video or the pokemon hw!

If you agree that this is something that needs fixing, I'd be happy to do it, if you'd be ammenable. Would be a great way for me to get some practice in, and hopefully helpful to take something off your plate!

**Comment by labrocadabro** [comment]
Thanks so much for pointing this out! Go ahead and make the PR, I really appreciate it. :)
